import { convexTest } from 'convex-test'
import { getAuthTables } from 'better-auth/db'
import { describe, expect, test } from 'vitest'
import { createAuthOptions } from './auth.ts'
import schema from './schema'
import betterAuthComponentSchema from './betterAuth/schema'
import { tables as upstreamTables } from './betterAuth/generatedSchema'
import { components } from './_generated/api'
import { makeRegisterBetterAuth } from './fixtures.ts'

// Supplied here, not in fixtures.ts: that file is PUSHED to the deployment and
// the Convex runtime has no import.meta. See makeRegisterBetterAuth's comment.
const registerBetterAuth = makeRegisterBetterAuth(import.meta.glob('./betterAuth/**/*.ts'))

const modules = import.meta.glob('./**/*.ts')

/**
 * THE MISTAKE THIS FILE EXISTS TO CATCH IS INVISIBLE TO TSC.
 *
 * `createApi` is generic over `Schema extends SchemaDefinition<any, any>`
 * (node_modules/@convex-dev/better-auth/src/client/create-api.ts:61), and BOTH
 * `./betterAuth/schema` and `./betterAuth/generatedSchema` satisfy it — they
 * export a `defineSchema(...)` each. So changing `adapter.ts`'s import from
 * `./schema` to `./generatedSchema` typechecks, lints, builds and deploys
 * completely clean while silently dropping `passkey` from the adapter's
 * argument-validator union. Same for anything that re-introduces the local
 * schema without our additions.
 *
 * Measured 2026-09-13 by making exactly that edit: `pnpm typecheck`, `pnpm
 * lint` and `pnpm build` all stayed green; only the second test below went red.
 */
describe('the betterAuth component schema', () => {
  /**
   * The structural half. Guards ./schema.ts itself: it must SPREAD upstream
   * rather than replace it (see the SchemaDefinitionError note in that file —
   * dropping a table or field that existing rows carry kills the push), and it
   * must carry the one table the whole local-component exercise exists for.
   */
  test('is a strict superset of the upstream generated tables', () => {
    const local = Object.keys(betterAuthComponentSchema.tables)
    const upstream = Object.keys(upstreamTables)

    // Superset: nothing upstream may go missing.
    expect(upstream.filter((name) => !local.includes(name))).toEqual([])

    // Strict: passkey is ours, and is deliberately absent upstream — which is
    // the entire reason this component was vendored (wordle-teams-hrqw).
    expect(local).toContain('passkey')
    expect(upstream).not.toContain('passkey')
  })

  /**
   * The wiring half, and the one that actually fails on the `./generatedSchema`
   * substitution. It asserts through the SAME path production uses —
   * `components.betterAuth.adapter.create`, which is what `createClient`'s
   * adapter calls — so it is red if EITHER the adapter is built from the wrong
   * schema OR the suite has drifted back to registering the package's copy of
   * the component instead of `convex/betterAuth/` (which is what it did until
   * the review of Task 2; see `registerBetterAuth` in fixtures.ts).
   *
   * A wrong schema here is an `ArgumentValidationError` on `model: 'passkey'`,
   * because the union is built from `schema.tables` and nothing else.
   */
  test('exposes passkey through the adapter the app actually calls', async () => {
    const t = convexTest(schema, modules)
    registerBetterAuth(t)

    const created = (await t.run((ctx) =>
      ctx.runMutation(components.betterAuth.adapter.create, {
        input: {
          model: 'passkey',
          data: {
            publicKey: 'pk',
            userId: 'user-1',
            credentialID: 'cred-1',
            counter: 0,
            deviceType: 'singleDevice',
            backedUp: false,
            createdAt: Date.now(),
          },
        },
        // NO CAST HERE ANY MORE, AND ITS ABSENCE IS LOAD-BEARING
        // (wordle-teams-ifbf). This argument used to be `as never`, because the
        // literal `model` union in `convex/betterAuth/_generated/component.ts`
        // is regenerated by `convex dev` against a running deployment and the
        // committed copy predated the passkey table. That file has now been
        // regenerated with `passkey` in the union, so the call typechecks on its
        // own merits — which means `pnpm typecheck` is now a second, static
        // check that the vendored component really does expose the model, and
        // it goes red if the generated file is ever rolled back or regenerated
        // against a deployment that lacks it. Do not restore the cast to make a
        // type error go away; regenerate the file instead.
      }),
    )) as { _id: string; credentialID: string }

    expect(created.credentialID).toBe('cred-1')
  })

  /**
   * THE FIX FOR wordle-teams-047w, ASSERTED WHERE IT ACTUALLY BITES.
   *
   * The plugin declares `credentialID` as `index: true`, not `unique: true`, so
   * NOTHING enforced uniqueness at any layer: registration calls
   * `adapter.create` with no prior lookup, authentication resolves a credential
   * with a plain `findOne` on the field, and a Convex index does not constrain.
   * `convex/betterAuth/adapter.ts` now marks the field unique on the options it
   * builds `createApi` from, which turns on the library's own
   * `checkUniqueFields` — so this goes green through the same mutation the real
   * adapter calls, not through a probe of the schema object.
   *
   * IT IS THE COMPLEMENT OF THE TRIPWIRE BELOW, and the two say different
   * things on purpose: that one reads the UNPATCHED `createAuthOptions` and
   * stays red-on-upstream-fix, this one reads the patched adapter and would go
   * red if the patch were dropped. Deleting the patch without deleting this
   * test is a failure, which is the point.
   *
   * THE FIRST INSERT IS PART OF THE ASSERTION. A `rejects` that fired because
   * the row was malformed, the model was missing from the validator union or
   * the component was never registered would look identical to a uniqueness
   * refusal; creating one successfully first rules all three out.
   */
  test('refuses a second passkey carrying a credentialID that already exists', async () => {
    const t = convexTest(schema, modules)
    registerBetterAuth(t)

    // Same credentialID, DIFFERENT everything else, so nothing but the field
    // under test can be what the second call trips on.
    const row = (userId: string) => ({
      publicKey: `pk-${userId}`,
      userId,
      credentialID: 'cred-shared',
      counter: 0,
      deviceType: 'singleDevice',
      backedUp: false,
      createdAt: Date.now(),
    })
    const create = (userId: string) =>
      t.run((ctx) =>
        ctx.runMutation(components.betterAuth.adapter.create, {
          input: { model: 'passkey', data: row(userId) },
        }),
      )

    await create('user-1')

    // `checkUniqueFields`'s own message (adapter-utils.ts:273) — matched rather
    // than a bare `rejects`, so a row rejected for any OTHER reason fails here.
    await expect(create('user-2')).rejects.toThrow(/passkey credentialID already exists/)
  })
})

/**
 * A TRIPWIRE FOR wordle-teams-047w, AND RED HERE IS GOOD NEWS: it means an
 * upstream version finally declares the field unique. When it fires, drop the
 * expectation below AND `withUniqueCredentialId` from
 * convex/betterAuth/adapter.ts — 047w was closed by patching the options this
 * app passes to `createApi`, which becomes redundant the moment the plugin does
 * it itself.
 *
 * THIS READS THE UNPATCHED OPTIONS, DELIBERATELY. `createAuthOptions` is what
 * builds the real Better Auth instance; the patch lives in adapter.ts and is
 * seen by nothing else. So this still measures UPSTREAM, which is the only
 * thing worth watching — the local enforcement is asserted end to end by
 * 'refuses a second passkey carrying a credentialID that already exists'
 * above, through the mutation the real adapter calls.
 *
 * WHAT IT IS NOT: an assertion that `credentialID` is non-unique. 047w is
 * explicit that pinning the current state that way locks the bug in. What is
 * pinned is the SET of unique fields on the model, which is the thing that
 * changes when the bug is fixed rather than the bug itself.
 *
 * THE SCHEMA THIS READS IS NOT THE CONVEX ONE ABOVE. `createApi` computes
 * `getAuthTables(createAuthOptions({}))` (create-api.ts:65) and uses it for
 * `checkUniqueFields` and nothing else, so this is the exact object the
 * uniqueness check consults — a Convex index, which convex/betterAuth/schema.ts
 * does declare on the field, constrains nothing.
 */
describe('the uniqueness the adapter actually enforces', () => {
  /**
   * Mirrors `isUniqueField`'s own predicate — it filters on `value.unique` and
   * nothing else (node_modules/@convex-dev/better-auth/src/client/
   * adapter-utils.ts:61-74) — so this tracks the real check rather than a
   * paraphrase of it.
   *
   * RETURNS `null` FOR A MODEL THAT IS NOT THERE, WHICH IS THE WHOLE POINT OF
   * THE HELPER. 047w's finding is that the passkey model went from "not found,
   * answer false" to "found, answer false": the reason changed and the outcome
   * did not. A helper that answered `[]` for both would report the two states
   * identically and this test would pass with the plugin ripped out of
   * `createAuthOptions` entirely.
   */
  const uniqueFieldsOf = (tables: ReturnType<typeof getAuthTables>, model: string) => {
    const fields = Object.values(tables).find((table) => table.modelName === model)?.fields
    if (!fields) return null
    return Object.entries(fields)
      .filter(([, field]) => (field as { unique?: boolean }).unique)
      .map(([name]) => name)
      .sort()
  }

  test('passkey has no unique fields, and user.email proves the probe can see one', () => {
    const tables = getAuthTables(createAuthOptions({} as never))

    // THE CONTROL, AND IT COMES FIRST DELIBERATELY. `user.email` is genuinely
    // declared unique, so a harness that had broken — wrong shape out of
    // `getAuthTables`, a `fields` object that is empty, a filter reading a
    // property that no longer exists — fails HERE rather than sailing through
    // the real assertion as a green light. Without it, `[]` below is equally
    // the answer to "nothing is unique" and to "this probe sees nothing at
    // all", which is precisely the pass-for-the-wrong-reason 047w's own
    // measurement was careful to rule out.
    expect(uniqueFieldsOf(tables, 'user')).toContain('email')

    // THE MODEL IS PRESENT AND CARRIES THE FIELD. `[]` from an ABSENT passkey
    // model — the plugin dropped from createAuthOptions — is the pre-wty4.1.7
    // state, not the bug this guards, and these two lines are what tells them
    // apart.
    const passkeyFields = Object.values(tables).find((table) => table.modelName === 'passkey')
      ?.fields
    expect(Object.keys(passkeyFields ?? {})).toContain('credentialID')

    // THE TRIPWIRE. Measured against @better-auth/passkey 1.6.23, whose schema
    // declares `credentialID: { type: 'string', required: true, index: true }`
    // — index, not unique (dist/index.mjs:648-651). When this goes red, see the
    // paragraph at the top of this describe.
    expect(uniqueFieldsOf(tables, 'passkey')).toEqual([])
  })
})
