import { convexTest } from 'convex-test'
import { describe, expect, test } from 'vitest'
import schema from './schema'
import betterAuthComponentSchema from './betterAuth/schema'
import { tables as upstreamTables } from './betterAuth/generatedSchema'
import { components } from './_generated/api'
import { makeRegisterBetterAuth } from './fixtures.ts'

// Supplied here, not in fixtures.ts: that file is PUSHED to the deployment and
// the Convex runtime has no import.meta. See makeRegisterBetterAuth's comment.
const registerBetterAuth = makeRegisterBetterAuth(import.meta.glob('./betterAuth/**/*.ts'))

const modules = import.meta.glob('./**/*.ts')

/**
 * THE MISTAKE THIS FILE EXISTS TO CATCH IS INVISIBLE TO TSC.
 *
 * `createApi` is generic over `Schema extends SchemaDefinition<any, any>`
 * (node_modules/@convex-dev/better-auth/src/client/create-api.ts:61), and BOTH
 * `./betterAuth/schema` and `./betterAuth/generatedSchema` satisfy it — they
 * export a `defineSchema(...)` each. So changing `adapter.ts`'s import from
 * `./schema` to `./generatedSchema` typechecks, lints, builds and deploys
 * completely clean while silently dropping `passkey` from the adapter's
 * argument-validator union. Same for anything that re-introduces the local
 * schema without our additions.
 *
 * Measured 2026-09-13 by making exactly that edit: `pnpm typecheck`, `pnpm
 * lint` and `pnpm build` all stayed green; only the second test below went red.
 */
describe('the betterAuth component schema', () => {
  /**
   * The structural half. Guards ./schema.ts itself: it must SPREAD upstream
   * rather than replace it (see the SchemaDefinitionError note in that file —
   * dropping a table or field that existing rows carry kills the push), and it
   * must carry the one table the whole local-component exercise exists for.
   */
  test('is a strict superset of the upstream generated tables', () => {
    const local = Object.keys(betterAuthComponentSchema.tables)
    const upstream = Object.keys(upstreamTables)

    // Superset: nothing upstream may go missing.
    expect(upstream.filter((name) => !local.includes(name))).toEqual([])

    // Strict: passkey is ours, and is deliberately absent upstream — which is
    // the entire reason this component was vendored (wordle-teams-hrqw).
    expect(local).toContain('passkey')
    expect(upstream).not.toContain('passkey')
  })

  /**
   * The wiring half, and the one that actually fails on the `./generatedSchema`
   * substitution. It asserts through the SAME path production uses —
   * `components.betterAuth.adapter.create`, which is what `createClient`'s
   * adapter calls — so it is red if EITHER the adapter is built from the wrong
   * schema OR the suite has drifted back to registering the package's copy of
   * the component instead of `convex/betterAuth/` (which is what it did until
   * the review of Task 2; see `registerBetterAuth` in fixtures.ts).
   *
   * A wrong schema here is an `ArgumentValidationError` on `model: 'passkey'`,
   * because the union is built from `schema.tables` and nothing else.
   */
  test('exposes passkey through the adapter the app actually calls', async () => {
    const t = convexTest(schema, modules)
    registerBetterAuth(t)

    const created = (await t.run((ctx) =>
      ctx.runMutation(components.betterAuth.adapter.create, {
        input: {
          model: 'passkey',
          data: {
            publicKey: 'pk',
            userId: 'user-1',
            credentialID: 'cred-1',
            counter: 0,
            deviceType: 'singleDevice',
            backedUp: false,
            createdAt: Date.now(),
          },
        },
        // The literal union in `convex/betterAuth/_generated/component.ts` is
        // regenerated by `npx convex dev` against a deployment, so it does not
        // know about `passkey` until this branch is pushed. The cast is about
        // codegen lag, not about the call being wrong — drop it once that file
        // has been regenerated.
      } as never),
    )) as { _id: string; credentialID: string }

    expect(created.credentialID).toBe('cred-1')
  })
})
