import { readFileSync } from 'node:fs'
import { describe, expect, test } from 'vitest'
import {
  APP_DEFAULT_TITLE,
  APP_DESCRIPTION,
  APP_NAME,
  CANONICAL_PATH_BY_ROUTE,
  NOINDEX_META,
  canonicalUrlFor,
  publicRouteHead,
  OG_IMAGE_ALT,
  OG_IMAGE_HEIGHT,
  OG_IMAGE_TYPE,
  OG_IMAGE_URL,
  OG_IMAGE_WIDTH,
  SITE_ORIGIN,
  socialMetaTags,
} from './lib/seo'
import {
  SITEMAP_CONTENT_TYPE,
  SITEMAP_ENTRIES,
  renderSitemap,
  sitemapResponse,
} from './lib/sitemap'
import {
  elementsOf,
  optionsPassedTo,
  propertiesOf,
  returnedObjectOf,
} from './test-support/source-ast'

/**
 * THE THREE ARTEFACTS NOBODY LOOKS AT UNTIL THEY ARE WRONG — public/robots.txt,
 * /sitemap.xml and the social card — AND THE ONE CHECK THAT SPANS THEM.
 *
 * WHY THESE ARE UNIT TESTS AND NOT ONLY e2e. .github/workflows/deploy-v2.yml
 * runs lint, typecheck, `vitest run` and build, then deploys and smoke-tests
 * /login. IT RUNS NO PLAYWRIGHT (wt-ksh.8.49), so an e2e-only protection is not
 * a gate — it is a thing somebody may run. Everything here is reachable from
 * `vitest run`, which is.
 *
 * WHY EVERY ASSERTION PARSES INSTEAD OF MATCHING. `expect(body).toContain(
 * 'Disallow: /app')` is the obvious test for a robots file and it is worth
 * almost nothing: it passes on a file that says `Allow: /app` two lines lower,
 * on one where the rule sits inside a comment, and on one with a second
 * User-agent group that overrides it. Eleven defects this phase were found only
 * because an assertion was moved off a substring of a blob and onto a parsed,
 * bounded value. So robots.txt is parsed into directives, the sitemap into url
 * records, the meta tags are imported as data, and the PNG's dimensions are
 * read out of its IHDR chunk.
 *
 * THE CHECK WORTH MORE THAN EITHER FILE'S OWN ASSERTIONS is the last describe
 * block. robots.txt and the sitemap are two files that talk about the same set
 * of URLs, maintained months apart by people who have read one of them. Nothing
 * makes them agree, and a sitemap entry for a path robots.txt forbids tells a
 * crawler two contradictory things about one URL. That is the check a human
 * would never do by hand, and it is a five-line loop here.
 */

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')

const ROBOTS = '../public/robots.txt'
const SITEMAP_ROUTE = './routes/sitemap[.]xml.ts'
const ROOT_ROUTE = './routes/__root.tsx'

/**
 * The social card image ON DISK, DERIVED FROM THE URL THE TAG CARRIES rather
 * than written out a second time. An independent literal here would go on
 * reading the right file no matter where og:image pointed, which defeats the
 * only thing this path is for: repointing og:image at a file public/ does not
 * hold has to go red, and against a literal it would not.
 */
const OG_IMAGE_FILE = `../public${new URL(OG_IMAGE_URL).pathname}`

/**
 * Every route path in the generated tree, deduplicated and sorted.
 *
 * routeTree.gen.ts is generated by the vite plugin and checked in, so this is
 * the app's real route list at this commit — and it is a BOUNDED LIST, which is
 * why both the `/sitemap.xml` registration check and the cross-file coverage
 * check below read it instead of matching a regex against the whole file.
 */
const routes = [
  ...new Set(
    [...read('./routeTree.gen.ts').matchAll(/^\s*path: '([^']*)',$/gm)].map((match) => match[1]),
  ),
].sort()

// ---------------------------------------------------------------------------
// robots.txt, parsed into the directives a crawler would act on.
// ---------------------------------------------------------------------------

interface RobotsGroup {
  userAgents: string[]
  allow: string[]
  disallow: string[]
}

interface Robots {
  groups: RobotsGroup[]
  sitemaps: string[]
  /** Any directive this parser does not know. Asserted empty: a typo is a bug. */
  unrecognised: string[]
}

/**
 * A robots.txt parser, deliberately strict.
 *
 * Comments run from `#` to end of line and are dropped BEFORE anything else, so
 * the long rationale at the top of the file cannot satisfy any assertion below
 * — the same reason src/routes.test.ts strips comments before reading route
 * source. Field names are case-insensitive per the standard; v1's generated
 * file writes `User-Agent` and this one writes `User-agent`.
 *
 * Consecutive `User-agent` lines form ONE group, which is the rule that makes
 * "there is exactly one group here" a meaningful thing to assert: a second
 * group with its own rules is precisely how a `Disallow` that reads correctly
 * stops applying to Googlebot.
 */
function parseRobots(text: string): Robots {
  const robots: Robots = { groups: [], sitemaps: [], unrecognised: [] }
  let group: RobotsGroup | null = null
  let previousWasUserAgent = false

  for (const raw of text.split('\n')) {
    const line = raw.replace(/#.*$/, '').trim()
    if (!line) continue

    const separator = line.indexOf(':')
    if (separator === -1) {
      robots.unrecognised.push(line)
      previousWasUserAgent = false
      continue
    }

    const field = line.slice(0, separator).trim().toLowerCase()
    const value = line.slice(separator + 1).trim()

    if (field === 'user-agent') {
      if (!previousWasUserAgent || !group) {
        group = { userAgents: [], allow: [], disallow: [] }
        robots.groups.push(group)
      }
      group.userAgents.push(value)
      previousWasUserAgent = true
      continue
    }

    previousWasUserAgent = false
    if (field === 'sitemap') robots.sitemaps.push(value)
    else if (field === 'allow' && group) group.allow.push(value)
    else if (field === 'disallow' && group) group.disallow.push(value)
    else robots.unrecognised.push(line)
  }

  return robots
}

const robots = parseRobots(read(ROBOTS))

describe('public/robots.txt', () => {
  test('is one group for every crawler, and nothing this parser cannot read', () => {
    // v2 shipped the Vite starter default until Phase 7 Task 8: a comment,
    // `User-agent: *` and an empty `Disallow:`, which allows everything.
    expect(robots.unrecognised).toEqual([])
    expect(robots.groups).toHaveLength(1)
    expect(robots.groups[0].userAgents).toEqual(['*'])
  })

  test('disallows exactly /app, /me, /complete-profile and /api', () => {
    // SORTED AND EXHAUSTIVE, not four toContain calls. The mutation a
    // `toContain('Disallow: /app')` cannot see is an ADDED rule — a
    // `Disallow: /privacy` slipped in beneath these would deindex the legal
    // pages and satisfy every positive assertion in the file.
    expect([...robots.groups[0].disallow].sort()).toEqual([
      '/api',
      '/app',
      '/complete-profile',
      '/me',
    ])
  })

  test('the /me rule has no trailing slash, which is where v1 gets it wrong', () => {
    // Production serves `Disallow: /me/` today. These are PREFIX rules, and
    // `/me/` is not a prefix of `/me`, so v1's dashboard — the page behind the
    // login — has been crawlable for the life of the project. v2's `/me` covers
    // the path and everything under it.
    expect(robots.groups[0].disallow).toContain('/me')
    expect(robots.groups[0].disallow).not.toContain('/me/')
  })

  test('allows everything else', () => {
    expect(robots.groups[0].allow).toEqual(['/'])
  })

  test('names one sitemap, at the production origin', () => {
    // THE LITERAL, not `${SITE_ORIGIN}/sitemap.xml` — building the expectation
    // from the same constant the code uses would pass whatever that constant
    // became. The second assertion is what ties the two together, and it is
    // the one that fails if only one of the pair is edited.
    expect(robots.sitemaps).toEqual(['https://wordleteams.com/sitemap.xml'])
    expect(robots.sitemaps[0]).toBe(`${SITE_ORIGIN}/sitemap.xml`)
  })
})

// ---------------------------------------------------------------------------
// The sitemap document, parsed into url records.
// ---------------------------------------------------------------------------

/**
 * The `<url>` entries of a urlset, each as a tag -> text record.
 *
 * There is no DOMParser under `environment: 'edge-runtime'` and no XML parser
 * in the tree, so this is hand-rolled — but it still yields BOUNDED VALUES. An
 * assertion below is about one entry's `<loc>`, never about "this string
 * appears somewhere in the document", and the key set of each record is
 * asserted too, which is what makes the absence of `<lastmod>` provable rather
 * than merely unobserved.
 */
function parseUrlset(xml: string): Array<Record<string, string>> {
  expect(xml.startsWith('<?xml version="1.0" encoding="UTF-8"?>\n')).toBe(true)

  const open = '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
  const start = xml.indexOf(open)
  const end = xml.indexOf('</urlset>')
  expect(start, 'no sitemaps.org urlset element').toBeGreaterThan(-1)
  expect(end, 'unclosed urlset element').toBeGreaterThan(start)

  const inner = xml.slice(start + open.length, end)
  const entries = [...inner.matchAll(/<url>([\s\S]*?)<\/url>/g)].map((match) =>
    Object.fromEntries(
      [...match[1].matchAll(/<(\w+)>([^<]*)<\/\1>/g)].map(([, tag, value]) => [tag, value]),
    ),
  )

  // Nothing may live between the <url> blocks. Without this a stray element
  // could sit in the urlset and no per-entry assertion would ever see it.
  expect(inner.replace(/<url>[\s\S]*?<\/url>/g, '').trim()).toBe('')
  return entries
}

const sitemap = parseUrlset(renderSitemap())

/** Every URL the sitemap advertises, as a path: the apex becomes '/'. */
const sitemapPaths = sitemap.map((entry) => new URL(entry.loc).pathname)

describe('/sitemap.xml', () => {
  test('lists v1’s seven URLs, in v1’s order, and nothing else', () => {
    // ABSOLUTE URLS SPELLED OUT. Asserting on paths alone would pass on a
    // sitemap of beta.wordleteams.com URLs, which is a request to index the
    // staging copy of the site.
    expect(sitemap.map((entry) => entry.loc)).toEqual([
      'https://wordleteams.com',
      'https://wordleteams.com/home',
      'https://wordleteams.com/about',
      'https://wordleteams.com/privacy',
      'https://wordleteams.com/terms',
      'https://wordleteams.com/login',
      'https://wordleteams.com/maintenance',
    ])
  })

  test('carries v1’s priorities and change frequencies', () => {
    expect(sitemap.map((entry) => entry.priority)).toEqual([
      '1',
      '0.9',
      '0.8',
      '0.7',
      '0.6',
      '0.5',
      '0.4',
    ])
    expect(sitemap.map((entry) => entry.changefreq)).toEqual([
      'monthly',
      'monthly',
      'monthly',
      'yearly',
      'yearly',
      'yearly',
      'yearly',
    ])
  })

  test('carries no <lastmod> on any entry, which is the one change from v1', () => {
    // v1 stamps `new Date()` on all seven, so every URL claims to have changed
    // at the moment the crawler asked — the exact signal that makes a site's
    // lastmod untrustworthy. The build date would be the same mistake more
    // slowly. See the argument in lib/sitemap.ts.
    //
    // BOTH DIRECTIONS. The key-set assertion is the bounded one; the whole-
    // document scan is a negative over a superset, which cannot pass falsely.
    for (const entry of sitemap) {
      expect(Object.keys(entry).sort()).toEqual(['changefreq', 'loc', 'priority'])
    }
    expect(renderSitemap()).not.toContain('lastmod')
  })

  test('every <loc> is an absolute URL at the canonical origin', () => {
    for (const entry of sitemap) {
      expect(new URL(entry.loc).origin).toBe('https://wordleteams.com')
    }
    // The rendered document and the entry table cannot disagree about how many
    // URLs there are.
    expect(sitemap).toHaveLength(SITEMAP_ENTRIES.length)
  })

  test('the response is application/xml and edge-cacheable for everyone', async () => {
    // THE REAL Response OBJECT, built by the function the route calls. This is
    // the assertion that would otherwise exist only in Playwright.
    const response = sitemapResponse()
    expect(response.status).toBe(200)
    expect(response.headers.get('content-type')).toBe('application/xml; charset=utf-8')
    expect(SITEMAP_CONTENT_TYPE).toBe('application/xml; charset=utf-8')

    // Unconditionally shareable, unlike an SSR document: this body is rendered
    // from a compile-time constant, reads no request and is byte-identical for
    // an anonymous crawler and a signed-in user, so lib/cache-policy.ts's
    // session dimension has nothing to attach to. The LITERAL, so that a change
    // to STATIC_CACHE has to be made here too.
    expect(response.headers.get('cache-control')).toBe(
      'public, max-age=0, s-maxage=86400, stale-while-revalidate=604800',
    )

    // NOT `private, no-store`. src/server.ts rewrites cache-control on any
    // text/html response and leaves everything else alone; this pins that the
    // content-type is on the correct side of that guard.
    expect(response.headers.get('cache-control')).not.toContain('no-store')

    expect(await response.text()).toBe(renderSitemap())
  })
})

describe('the /sitemap.xml route is still wired to that response', () => {
  // The wiring is the one part of this feature no imported function can reach:
  // src/routes/sitemap[.]xml.ts calls createFileRoute, which cannot be imported
  // under vitest. Parsed with the compiler rather than matched, for the reason
  // in test-support/source-ast.ts — a literal in a dead `const` has passed
  // every gate and every e2e test twice in this phase.
  const options = () =>
    optionsPassedTo(SITEMAP_ROUTE, read(SITEMAP_ROUTE), "createFileRoute('/sitemap.xml')")

  test('registers exactly one handler, GET', () => {
    const handlers = propertiesOf(propertiesOf(options().get('server')!).get('handlers')!)
    expect([...handlers.keys()]).toEqual(['GET'])
    // The handler expression itself, bounded to that property's initializer —
    // not "sitemapResponse appears in this file", which the module's own doc
    // comment would satisfy on its own.
    expect(handlers.get('GET')!.getText()).toMatch(
      /^withErrorCapture\(\s*'\/sitemap\.xml GET',\s*\(\) => sitemapResponse\(\),?\s*\)$/,
    )
  })

  test('is in the generated route tree, so the [.] escape really resolved', () => {
    // `sitemap[.]xml.ts` without the brackets registers as `/sitemap/xml` and
    // every unit test above still passes — this is the only place that shows.
    // routeTree.gen.ts is checked in, so it is an artefact of the commit. The
    // assertion is on the PARSED route list, not on a regex over the file: the
    // same bounded value the coverage check below uses.
    expect(routes).toContain('/sitemap.xml')
  })
})

// ---------------------------------------------------------------------------
// The social card.
// ---------------------------------------------------------------------------

/** The exact strings production serves, read off `curl https://wordleteams.com/home`. */
const PROD_TITLE = 'Wordle Teams: The ultimate app for Wordle enthusiasts'
const PROD_DESCRIPTION =
  'Wordle Teams lets you compete with friends by tracking and comparing your Wordle scores, adding a competitive edge to the popular word-guessing game. Stay ahead of the competition, enjoy friendly rivalry, and prove your Wordle mastery with this exciting score-tracking app. Revive the Wordle craze and bring your A-game to the ultimate word-guessing showdown with Wordle Teams!'

const metaKey = (tag: (typeof socialMetaTags)[number]) =>
  'name' in tag ? tag.name : tag.property

describe('the OpenGraph and Twitter card', () => {
  test('every tag is declared once', () => {
    // A duplicate og:title is not a compile error and not a visible one either:
    // scrapers take the first, or the last, depending on the scraper.
    const keys = socialMetaTags.map(metaKey)
    expect([...new Set(keys)]).toHaveLength(keys.length)
  })

  test('matches, tag for tag, what production emits today', () => {
    // v1's values were read OFF THE LIVE DOCUMENT, not reconstructed from its
    // `metadata` object — Next expands one image descriptor into four tags with
    // rules of its own, and this is a parity port of the OUTPUT.
    //
    // THE ATTRIBUTE FORM FIRST, AND IT IS NOT COSMETIC. Production's split is
    // exact: `description` and every `twitter:*` are `name=`, every `og:*` is
    // `property=`. `<meta name="og:image">` is ignored outright by the
    // OpenGraph parsers in Facebook, LinkedIn, Slack and Discord — the shared
    // card silently loses its picture. Nothing else in the repo can see it:
    // metaKey() below flattens the two attributes into one key by design, and
    // the e2e locator is `meta[property="x"], meta[name="x"]`, which matches
    // either by construction. So the pair is asserted, in order, all eighteen.
    //
    // EIGHTEEN, NOT NINETEEN, SINCE wt-ksh.8.55: og:url has left this list.
    // THE RENDERED DOCUMENT STILL CARRIES IT, so this is still a parity port of
    // production's OUTPUT — what changed is that the tag is now declared by the
    // route rather than site-wide, because v1's single site-wide value made
    // every page announce itself as the home page. It is asserted per route in
    // "publicRouteHead emits og:url and rel=canonical, and they agree" below,
    // and its absence HERE is asserted too, so it cannot quietly come back and
    // ship two of them.
    expect(
      socialMetaTags.map((tag) => ('name' in tag ? ['name', tag.name] : ['property', tag.property])),
    ).toEqual([
      ['name', 'description'],
      ['property', 'og:title'],
      ['property', 'og:description'],
      ['property', 'og:site_name'],
      ['property', 'og:image:type'],
      ['property', 'og:image:width'],
      ['property', 'og:image:height'],
      ['property', 'og:image:alt'],
      ['property', 'og:image'],
      ['property', 'og:type'],
      ['name', 'twitter:card'],
      ['name', 'twitter:title'],
      ['name', 'twitter:description'],
      ['name', 'twitter:image:type'],
      ['name', 'twitter:image:width'],
      ['name', 'twitter:image:height'],
      ['name', 'twitter:image:alt'],
      ['name', 'twitter:image'],
    ])

    // The whole map at once, so an ADDED tag fails as loudly as a changed one.
    expect(Object.fromEntries(socialMetaTags.map((tag) => [metaKey(tag), tag.content]))).toEqual({
      description: PROD_DESCRIPTION,
      'og:title': PROD_TITLE,
      'og:description': PROD_DESCRIPTION,
      'og:site_name': 'Wordle Teams',
      'og:image:type': 'image/png',
      'og:image:width': '1200',
      'og:image:height': '630',
      'og:image:alt': 'Wordle Teams',
      'og:image': 'https://wordleteams.com/opengraph-image.png',
      'og:type': 'website',
      'twitter:card': 'summary_large_image',
      'twitter:title': PROD_TITLE,
      'twitter:description': PROD_DESCRIPTION,
      'twitter:image:type': 'image/png',
      'twitter:image:width': '1200',
      'twitter:image:height': '630',
      'twitter:image:alt': 'Wordle Teams',
      'twitter:image': 'https://wordleteams.com/opengraph-image.png',
    })
  })

  test('the constants the rest of the app shares hold those same values', () => {
    // The map above pins the TAGS. These pin the CONSTANTS, which routes and
    // lib/seo.ts's pageTitle() also read — so the two cannot be split by
    // editing one and leaving the other.
    expect(APP_DEFAULT_TITLE).toBe(PROD_TITLE)
    expect(APP_DESCRIPTION).toBe(PROD_DESCRIPTION)
    expect(APP_NAME).toBe('Wordle Teams')
    expect(OG_IMAGE_ALT).toBe('Wordle Teams') // v1's opengraph-image.alt.txt
    expect(OG_IMAGE_TYPE).toBe('image/png')
    expect(OG_IMAGE_URL).toBe('https://wordleteams.com/opengraph-image.png')
  })

  test('twitter:image and og:image are the same asset, deliberately', () => {
    // v1 ships two byte-identical 196KB PNGs and points one tag at each,
    // because Next's file convention gave it opengraph-image.png and
    // twitter-image.png. v2 ships one. If these ever diverge it should be
    // because somebody drew a second picture.
    const tags = new Map(socialMetaTags.map((tag) => [metaKey(tag), tag.content]))
    expect(tags.get('twitter:image')).toBe(tags.get('og:image'))
  })

  test('the declared dimensions are the ones in the PNG that ships', () => {
    // READ OUT OF THE FILE'S IHDR CHUNK. og:image:width and og:image:height are
    // strings in a meta tag; nothing else in this repo could notice them being
    // wrong, and a scraper that trusts them renders a stretched card. Uint8Array
    // rather than Buffer: the vitest environment is edge-runtime.
    const bytes = new Uint8Array(readFileSync(new URL(OG_IMAGE_FILE, import.meta.url)))
    expect([...bytes.subarray(0, 8)]).toEqual([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])
    expect(String.fromCharCode(...bytes.subarray(12, 16))).toBe('IHDR')

    const header = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength)
    expect(header.getUint32(16)).toBe(1200)
    expect(header.getUint32(20)).toBe(630)
    expect(OG_IMAGE_WIDTH).toBe(1200)
    expect(OG_IMAGE_HEIGHT).toBe(630)
  })

  test('og:image’s pathname names a file that is really in public/', () => {
    // NOT a restatement of the map above, which already pins the whole URL.
    // OG_IMAGE_FILE is DERIVED from OG_IMAGE_URL, so this resolves the pathname
    // THE TAG CARRIES against public/ and reads it: repoint og:image at
    // /og.png and this goes red with ENOENT, where the map assertion would
    // simply be edited to match. A social card with a 404 for an image is the
    // failure mode nobody sees until a link is shared.
    //
    // readFileSync THROWING IS THE ASSERTION. A `byteLength` check underneath
    // it would be unreachable — the read fails first — which is how the
    // original version of this test managed to assert nothing at all.
    expect(() => readFileSync(new URL(OG_IMAGE_FILE, import.meta.url))).not.toThrow()
  })

  test('__root.tsx really spreads the tags into head().meta', () => {
    // The only unimported link in the chain. Deleting `...socialMetaTags` from
    // the root head leaves every assertion above green and ships a site with no
    // description and no social card.
    const root = optionsPassedTo(
      ROOT_ROUTE,
      read(ROOT_ROUTE),
      'createRootRouteWithContext<RouterContext>()',
    )
    const meta = elementsOf(propertiesOf(returnedObjectOf(root.get('head')!)).get('meta')!)
    expect(meta.filter((element) => element === '...socialMetaTags')).toHaveLength(1)
  })
})

// ---------------------------------------------------------------------------
// The check that spans the files.
// ---------------------------------------------------------------------------

/** robots.txt rules are prefix matches on the path. */
const disallowedBy = (pathname: string) =>
  robots.groups[0].disallow.filter((rule) => rule !== '' && pathname.startsWith(rule))

describe('robots.txt and the sitemap cannot contradict each other', () => {
  test('nothing the sitemap advertises is disallowed', () => {
    // THE POINT OF THIS FILE. Two artefacts describing one set of URLs, edited
    // months apart by people who have read one of them. A sitemap entry for a
    // path robots.txt forbids fetching asks a crawler to index a page it is not
    // allowed to read, and it resolves that by ignoring one of the two.
    const contradictions = sitemapPaths
      .map((pathname) => [pathname, disallowedBy(pathname)] as const)
      .filter(([, rules]) => rules.length > 0)
    expect(contradictions).toEqual([])
  })

  test('the sitemap URL robots.txt names is not itself disallowed', () => {
    expect(disallowedBy(new URL(robots.sitemaps[0]).pathname)).toEqual([])
  })

  test('every route in the app is listed, disallowed, or deliberately neither', () => {
    /**
     * THE CHECK THAT MAKES THE NEXT ROUTE A DECISION INSTEAD OF AN OMISSION.
     *
     * routeTree.gen.ts is generated by the vite plugin and checked in, so it is
     * the app's real route list at this commit. Every path in it must be
     * accounted for one of three ways, and the third has to be written down
     * here — which is the whole mechanism: adding a route without thinking
     * about crawlers turns this red with the path's name in the failure.
     */
    const NEITHER = new Map([
      [
        '/login-error',
        'New in v2 (Task 6) and NOT disallowed — there is no harm in a crawler ' +
          'that finds it, the page is four sentences and a link. But a sitemap says ' +
          '"these are worth showing a searcher", and a dead-end error page reachable ' +
          'only mid sign-in is not. Nothing links to it either way.',
      ],
      ['/sitemap.xml', 'The sitemap does not list itself.'],
    ])

    // The generated tree is the input to everything below, so a change to its
    // shape must not quietly turn this into a test of nothing.
    expect(routes.length, 'no route paths parsed out of routeTree.gen.ts').toBeGreaterThan(10)

    const unaccounted = routes.filter(
      (path) =>
        !sitemapPaths.includes(path) && disallowedBy(path).length === 0 && !NEITHER.has(path),
    )
    expect(
      unaccounted,
      'these routes are in neither the sitemap nor robots.txt. Decide: advertise ' +
        'it in lib/sitemap.ts, exclude it in public/robots.txt, or add it to ' +
        'NEITHER above with the reason.',
    ).toEqual([])

    // The converse, so a stale exclusion cannot outlive its route.
    expect([...NEITHER.keys()].filter((path) => !routes.includes(path))).toEqual([])

    // And so a REDUNDANT one cannot sit here unnoticed either. An entry for a
    // path the sitemap already advertises, or that robots.txt already
    // disallows, is a written-down decision that contradicts the artefact it
    // claims to explain — and without this line adding one leaves every test
    // in the file green.
    expect(
      [...NEITHER.keys()].filter(
        (path) => sitemapPaths.includes(path) || disallowedBy(path).length > 0,
      ),
      'these paths are already accounted for by the sitemap or by robots.txt, ' +
        'so their NEITHER entry is stale. Delete it.',
    ).toEqual([])

    // And the sitemap may only advertise paths that exist. A URL in a sitemap
    // that 404s is the one sitemap error Search Console actually reports.
    expect(sitemapPaths.filter((path) => !routes.includes(path))).toEqual([])
  })
})


// ---------------------------------------------------------------------------
// Canonical URLs and og:url (wt-ksh.8.55).
// ---------------------------------------------------------------------------

/**
 * THE THREE WAYS THIS GOES WRONG, one describe block each.
 *
 * v1 set og:url site-wide and let every page claim to be the home page, so a
 * scraper that dedupes on it treats the whole site as one document. And `/` and
 * /home render the same component and are both advertised, which is duplicate
 * content submitted twice with nothing saying which wins.
 *
 * The assertions below are on the DATA and on the ROUTE SOURCE, not on a
 * rendered document, for the reason this whole file exists: vitest is the CI
 * gate and there is no DOM in it. e2e/routes.spec.ts checks the rendered head.
 */
describe('the site-wide card no longer claims a URL', () => {
  test('og:url is absent from socialMetaTags', () => {
    // If it comes back, every route ships two og:url tags — the root's and its
    // own — which is worse than the single wrong one this replaced.
    //
    // WIDENED TO string[] ON PURPOSE. socialMetaTags is `as const`, so with
    // og:url removed TypeScript knows the comparison can never be true and
    // rejects it as an error rather than compiling a test that always passes.
    // That is a stronger guarantee than this assertion — the type is now the
    // real gate — but it only holds while the array stays literal, so the
    // runtime check stays as the one that survives someone typing the list.
    const keys: readonly string[] = socialMetaTags.map(metaKey)
    expect(keys).not.toContain('og:url')
  })
})

describe('every advertised URL declares a canonical', () => {
  test('the canonical table covers exactly the sitemap, no more and no less', () => {
    // A route added to one and not the other is the drift this pins. Sorted
    // rather than set-compared so the failure message names the difference.
    expect(Object.keys(CANONICAL_PATH_BY_ROUTE).sort()).toEqual(
      SITEMAP_ENTRIES.map((entry) => entry.path).sort(),
    )
  })

  test('each route canonicalises to its own sitemap <loc>, except /home', () => {
    for (const pathname of sitemapPaths) {
      const routePath = pathname === '/' ? '' : pathname
      if (routePath === '/home') continue
      const loc = sitemap.find((entry) => new URL(entry.loc).pathname === pathname)!.loc
      expect(canonicalUrlFor(routePath), `${pathname} canonical`).toBe(loc)
    }
  })

  test('/home canonicalises to the apex, because it is the same page as /', () => {
    // The one deliberate non-self-reference, and the reason the mapping is a
    // table. Asserted against `/`'s own canonical rather than a retyped literal
    // so the two cannot drift.
    expect(canonicalUrlFor('/home')).toBe(canonicalUrlFor(''))
    expect(canonicalUrlFor('/home')).toBe(SITE_ORIGIN)
  })

  test('an undeclared route throws rather than guessing', () => {
    // Silently returning SITE_ORIGIN + path would hand a new app route a
    // canonical it should not have. Failing loudly at the call site is the
    // point of the table.
    expect(() => canonicalUrlFor('/app')).toThrow(/No canonical declared/)
  })
})

describe('publicRouteHead emits og:url and rel=canonical, and they agree', () => {
  for (const routePath of Object.keys(CANONICAL_PATH_BY_ROUTE)) {
    test(`"${routePath || '/'}" declares one canonical and one matching og:url`, () => {
      const head = publicRouteHead(routePath)
      const ogUrl = head.meta.filter((tag) => 'property' in tag && tag.property === 'og:url')
      const canonical = head.links.filter((link) => link.rel === 'canonical')
      expect(ogUrl).toHaveLength(1)
      expect(canonical).toHaveLength(1)
      // THE ASSERTION THAT MATTERS: the two tags answer the same question, so
      // disagreeing is worse than either answer alone.
      expect(ogUrl[0].content).toBe(canonical[0].href)
      expect(canonical[0].href).toBe(canonicalUrlFor(routePath))
    })
  }
})

describe('the route files really call it', () => {
  /**
   * THE UNIMPORTED LINK IN THE CHAIN, exactly as the __root.tsx spread test
   * above. Everything else here asserts a pure function that no route has to
   * use. Deleting `head:` from a route file leaves all of it green and ships a
   * page with no canonical at all.
   */
  const ROUTE_FILES: Readonly<Record<string, string>> = {
    '': './routes/index.tsx',
    '/home': './routes/home.tsx',
    '/about': './routes/about.tsx',
    '/privacy': './routes/privacy.tsx',
    '/terms': './routes/terms.tsx',
    '/login': './routes/login.tsx',
    '/maintenance': './routes/maintenance.tsx',
  }

  test('every route in the canonical table has a file listed here', () => {
    expect(Object.keys(ROUTE_FILES).sort()).toEqual(Object.keys(CANONICAL_PATH_BY_ROUTE).sort())
  })

  for (const [routePath, file] of Object.entries(ROUTE_FILES)) {
    test(`${file} calls publicRouteHead('${routePath}')`, () => {
      const source = read(file)
      // Matched on the CALL WITH ITS OWN PATH, not merely on the identifier:
      // passing another route's path is the mistake that produces a confidently
      // wrong canonical, and it is invisible in a rendered page.
      expect(source).toContain(`publicRouteHead('${routePath}'`)
    })
  }
})


// ---------------------------------------------------------------------------
// noindex on the two routes that must never be a search result (wt-ksh.8.58).
// ---------------------------------------------------------------------------

describe('the outage page and the sign-in dead end are noindexed', () => {
  /**
   * A SITEMAP IS AN INVITATION, NOT A GATE, which is the whole reason this
   * needed a tag rather than a sitemap edit. Both routes answer 200 and are
   * reachable, so both are indexable regardless of what the sitemap says —
   * /maintenance IS listed and /login-error deliberately is not, and neither
   * fact affects indexability.
   *
   * NOT COVERED BY lib/robots-policy.ts. That sends X-Robots-Tag on the staging
   * HOSTNAMES and stops at cutover by design; this travels with the page, so it
   * is what protects these routes on PRODUCTION.
   */
  /**
   * THE HEAD THE ROUTE ACTUALLY PRODUCES, not the text of the file.
   *
   * The first version of this matched the source for `NOINDEX_META` and failed
   * on /maintenance — which reaches the tag through
   * `publicRouteHead(..., { noindex: true })` and never names the constant. Two
   * routes, two spellings, one outcome; asserting the outcome is both correct
   * and stronger, since it would catch a route that imported the constant and
   * forgot to put it in the array.
   */
  const headOf = (route: unknown) =>
    (route as { options: { head: () => { meta: unknown[] } } }).options.head().meta

  test('/maintenance asks not to be indexed', async () => {
    const { Route } = await import('./routes/maintenance.tsx')
    expect(headOf(Route)).toContainEqual(NOINDEX_META)
  })

  test('/login-error asks not to be indexed', async () => {
    const { Route } = await import('./routes/login-error.tsx')
    expect(headOf(Route)).toContainEqual(NOINDEX_META)
  })

  test('the tag is the one search engines actually read', () => {
    // `name="robots"`, not `property=` — the OpenGraph parsers ignore `name`
    // and the crawlers ignore `property`, and crawler-metadata's own parity
    // test records how easily that pair gets swapped.
    expect(NOINDEX_META).toEqual({ name: 'robots', content: 'noindex' })
  })

  test('publicRouteHead only adds it when asked', () => {
    // The default must stay indexable: every marketing route goes through this
    // helper, and a noindex leaking into them would remove the site from search.
    expect(publicRouteHead('/about', 'About').meta).not.toContainEqual(NOINDEX_META)
    expect(publicRouteHead('/maintenance', undefined, { noindex: true }).meta).toContainEqual(
      NOINDEX_META,
    )
  })
})
