import accepted from './data/accepted-guesses.json'

/**
 * The accepted-guess list, as a frozen array and a Set.
 *
 * A JSON import rather than a `?raw` text import or a generated .ts module:
 * JSON is handled natively by both vite and vitest with no bundler feature to
 * depend on, and it keeps a 12972-entry generated file out of the lint and
 * typecheck paths.
 *
 * Generated by scripts/fetch-wordlists.mjs. Do not hand-edit; see that file for
 * why the list is knowingly incomplete relative to today's NYT set.
 */
const WORDS: ReadonlyArray<string> = Object.freeze(accepted as Array<string>)
const LOOKUP = new Set(WORDS)

export function acceptedGuesses(): ReadonlyArray<string> {
  return WORDS
}

export function isAccepted(word: string): boolean {
  return LOOKUP.has(word.toUpperCase())
}
